singularity.runOptions = '-B "$HOME" -C -H "$PWD"'
report.overwrite = true
process{
  executor = 'slurm'
  queue    = 'cpu-single'
 
  withName:'segmentation:worker' {
    cpus     = 8
    time     = '8h'
    memory   = '64GB'
  }

}
plugins{
        id 'nf-co2footprint@1.0.0'
}

